### ISSUE TITLE
Leaflet "source" popups aren't clickable (?)

### ISSUE THREAD

**Issue by jack-davison** [posit-marketing/taylor-swift-tour#2]
Good afternoon,

This is an excellent demo of Quarto, thanks - learned a lot from it!

The `{leaflet}` map is really nice, but I'm a bit confused; the popups each have a "source" link, but I can't seem to click on them. As they're hover-labels, when you move your mouse towards "source" the hover closes. Should they be traditional popups, which linger rather than track the mouse, instead?

![image](https://github.com/posit-marketing/taylor-swift-tour/assets/45171616/78fbb6bd-47df-4a83-ab4d-f19e31e772e2)

Cheers,
Jack

**Comment by ivelasq** [comment]
Hi Jack, thanks for reaching out and we hope that you enjoyed the piece!

I have updated the map to use popups instead of labels, so you should be able to click the sources now.
In case it's easier, the sources are also available in this CSV: https://github.com/posit-marketing/taylor-swift-tour/blob/main/data/taylor-economic-impact_geocoded.csv

**Comment by jack-davison** [comment]
That's great, thanks! Just wanted to make sure I wasn't missing something as to how `{leaflet}` labels worked, really!

Cheers

**Comment by ivelasq** [comment]
Whoops 🫣 sorry about that!
